<?php

namespace Elchristo\Calendar\Service\Color;

use Elchristo\Calendar\Model\Event\ColoredEventInterface;

/**
 * Interface to apply color strategies to calendar events
 */
interface ColorStrategyInterface
{
    /**
     * Return color code generated by the strategy
     *
     * @return string Color code
     */
    public function getColorCodeByEvent();

    /**
     * Return color codes from configuration
     *
     * @return array
     */
    public function getColorConfig();

    /**
     * Inject color configuration
     *
     * @param array $config
     */
    public function setColorConfig(array $config);

    /**
     * Return the calendar event
     *
     * @return ColoredEventInterface
     */
    public function getEvent();

    /**
     * Inject calendar event into color strategy
     *
     * @param ColoredEventInterface $event
     */
    public function setEvent(ColoredEventInterface $event);

    /**
     * @return array
     */
    public function getAttributes();

    /**
     *
     * @param array $attributes
     */
    public function setAttributes(array $attributes = []);
}
