language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
sudo: false
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
 env:
  global:
    - COMPOSER_ARGS="--no-interaction"
install:
  - composer self-update && composer --version
  - composer install $COMPOSER_ARGS
branches:
  only: master
script:
  - php vendor/bin/codecept run cli,unit