language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
sudo: false
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
install:
  - composer self-update && composer --version
  - composer install --no-interaction
branches:
  only: master
script:
  - php vendor/bin/codecept run cli,unit
  - php vendor/bin/phpstan analyze ./